name: festim-review-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib=3.8.3
  - numpy<1.25
  - scipy==1.12.0
  - paraview=5.11.2=*_egl
  - pip:
    - festim==1.1.1
    - meshio[all]==5.3.5
