name: festim-review-env
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib
  - numpy<1.25
  - scipy
  - paraview=5.11.2=*_egl
  - pip:
    - festim==1.1.1
    - meshio[all]
