name: Run FESTIM scripts

on: pull_request

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: remdelaportemathurin/festim/setup_env@beta

    - name: Run Python scripts
      shell: bash -l {0}
      run: |
        cd comparison/tmap8
        python runner_festim.py