name: Run FESTIM scripts

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/setup_env.yml

  run:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python scripts
      shell: bash -l {0}
      run: |
        cd comparison/tmap8
        python runner_festim.py